apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: default
stringData:
  WORDPRESS_PASSWORD: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
  namespace: default
data:
  wp-config.php: |-
    $scheme = 'http://';
    if ( 'on' === $_SERVER['HTTPS'] ) {
      $scheme = 'https://';
    }

    if ( ! defined( 'WP_HOME' ) ) {
      define( 'WP_HOME', rtrim( getenv( 'WP_HOME' ) ?: $scheme . $_SERVER['HTTP_HOST'], '/' ) );
    }

    if ( ! defined( 'WP_SITEURL' ) ) {
      define( 'WP_SITEURL', rtrim( getenv( 'WP_SITEURL' ), '/' ) ?: WP_HOME . '/wp' );
    }
    unset( $scheme );

    if ( ! defined( 'AUTOMATIC_UPDATER_DISABLED' ) ) {
      define( 'AUTOMATIC_UPDATER_DISABLED', true );
    }

    if ( ! defined( 'DISABLE_WP_CRON' ) ) {
      define( 'DISABLE_WP_CRON', getenv( 'DISABLE_WP_CRON' ) ?: false );
    }

    if ( ! defined( 'DISALLOW_FILE_EDIT' ) ) {
      // Disable the plugin and theme file editor in the admin
      define( 'DISALLOW_FILE_EDIT', "true" === strtolower( getenv( 'DISALLOW_FILE_EDIT' ) ?: "true" ) );
    }

    if ( ! defined( 'DISALLOW_FILE_MODS' ) ) {
      // Disable plugin and theme updates and installation from the admin
      define( 'DISALLOW_FILE_MODS', "true" === strtolower( getenv( 'DISALLOW_FILE_MODS' ) ?: "true" ) );
    }
---
apiVersion: core.boundless.software/v1alpha1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  pod:
    containers:
      wordpress:
        image:
          repository: bitnami/wordpress
          tag: "6.0.2"
        env:
        - name: APACHE_HTTP_PORT_NUMBER
          value: "80"
        - name: WORDPRESS_USERNAME
          value: admin
        - name: WORDPRESS_EMAIL
          value: "sales@boundless.software"
        - name: WORDPRESS_FIRST_NAME
          value: Switchblade
        - name: WORDPRESS_LAST_NAME
          value: Operator
        - name: WORDPRESS_BLOG_NAME
          value: Switchblade
        - name: WORDPRESS_DATABASE_HOST
          value: mysql.default.svc.cluster.local
        - name: WORDPRESS_DATABASE_NAME
          value: wordpress
        - name: WORDPRESS_DATABASE_USER
          value: wordpress
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-db
              key: MYSQL_PASSWORD
        - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: "wp-config.php"
        envFrom:
        - secretRef:
            name: wordpress
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        ports:
        - 80
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /bitnami/wordpress
          name: wordpress
    volumes:
    - name: wordpress
      hostPath:
        path: /mnt/data/wordpress
        type: DirectoryOrCreate
  rbac:
    enabled: true
  service:
    ports:
    - name: http-wp
      port: 80
      protocol: TCP
  istio:
    virtualService:
      gateways:
      - istio-system/default-gateway
      hosts:
      - workstation-romil.boundless.software
      http:
      - destination:
          host: wordpress.default.svc.cluster.local
          port:
            number: 80
