apiVersion: v1
kind: Secret
metadata:
  name: wp-db
  namespace: default
stringData:
  MYSQL_PASSWORD: wordpress
---
apiVersion: core.boundless.software/v1alpha1
kind: Statefulset
metadata:
  name: mysql
  namespace: default
spec:
  pod:
    containers:
      mysql:
        image:
          repository: mysql
          tag: "5.7"
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "1"
        envFrom:
        - secretRef:
            name: wp-db
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        ports:
        - 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: wordpress-db
    volumes:
    - name: wordpress-db
      hostPath:
        path: /mnt/data/mysql
        type: DirectoryOrCreate
  service:
    ports:
    - name: tcp-mysql
      port: 3306
      protocol: TCP
  rbac:
    enabled: true
