apiVersion: core.boundless.software/v1alpha1
kind: Stack
metadata:
  name: switchbladedemo
  name: switchbladedemo
spec:
  aws:
    vpc:
      kurt-test:
        spec:
          provider:
            region: us-east-1
          cidrBlock: "10.0.10.0/16"
          subnets:
            - zone: us-east-1a
              cidrBlock: "10.0.0.0/24"
              type: private
            - zone: us-east-1b
              cidrBlock: "10.0.1.0/24"
              type: private
            - zone: us-east-1c
              cidrBlock: "10.0.10.0/24"
              type: private
      kurt-test2:
        spec:
          provider:
            region: us-east-2
          cidrBlock: "10.0.10.0/16"
          subnets:
            - zone: us-east-2a
              cidrBlock: "10.0.0.0/24"
              type: private
            - zone: us-east-2b
              cidrBlock: "10.0.1.0/24"
              type: private
            - zone: us-east-2c
              cidrBlock: "10.0.10.0/24"
              type: private
    rds:
      rds-sample:
        dependsOn:
          - name: kurt-test
            kind: Vpc
            valuePath: .subnets[10.0.0.0/24].id
            valuePathToReplace: .clusters[cluster1].subnetGroup.subnets[0]
          - name: kurt-test
            kind: Vpc
            valuePath: .subnets[10.0.1.0/24].id
            valuePathToReplace: .clusters[cluster1].subnetGroup.subnets[1]
          - name: kurt-test
            kind: Vpc
            valuePath: .subnets[10.0.10.0/24].id
            valuePathToReplace: .clusters[cluster1].subnetGroup.subnets[2]
          - name: kurt-test2
            kind: Vpc
            valuePath: .subnets[10.0.0.0/24].id
            valuePathToReplace: .clusters[cluster2].subnetGroup.subnets[0]
          - name: kurt-test2
            kind: Vpc
            valuePath: .subnets[10.0.1.0/24].id
            valuePathToReplace: .clusters[cluster2].subnetGroup.subnets[1]
          - name: kurt-test2
            kind: Vpc
            valuePath: .subnets[10.0.10.0/24].id
            valuePathToReplace: .clusters[cluster2].subnetGroup.subnets[2]
        spec:
          provider:
            region: us-east-1
          globalCluster:
            engine: aurora-mysql
          clusters:
            cluster1:
              provider:
                region: us-east-1
              subnetGroup:
                subnets:
                  - sdfds
                  - subdsf
                  - sudsfd
              parameterGroup:
                family: aurora-mysql8.0
              username: username
              tags:
                something: one
                something: two
                something: three
              password: Password123!
              engine: aurora-mysql
              backupRetentionPeriod: 5
              availabilityZones:
                - us-east-1a
              instances:
                instance1:
                  class: db.r5.xlarge
                # instance2:
                #   class: db.r5.xlarge
            cluster2:
              provider:
                region: us-east-2
              subnetGroup:
                subnets:
                  - value
                  - value
                  - value
              parameterGroup:
                family: aurora-mysql8.0
              username: username
              password: password
              engine: aurora-mysql
              backupRetentionPeriod: 5
              availabilityZones:
                - us-east-2a
            #   instances:
            #     instance1:
            #       class: db.r5.xlarge