apiVersion: aws.boundless.software/v1alpha1
kind: Ecr
metadata:
  name: example-ecr
spec:
  provider:
    region: us-east-1
  repository:
    name: example-repo
    tags:
      - latest
      - <tag>
