apiVersion: aws.boundless.software/v1alpha1
kind: Lambda
metadata:
  name: example-lambda
spec:
  provider:
    region: us-east-1
  runtime: "nodejs14.x"
  architecture: "x86_64"
  role: "arn:aws:iam::<account-id>:role/example-lambda-role"
  handler: "index.handler"
  code:
    s3Bucket: switchblade-state
    s3Key: lambda/function.zip
  description: "This is a test lambda function"
  timeout: 10 # Time in seconds
  memorySize: 200 # Memory size in MB
  publish: true # Set to true to publish the first version of the function during creation
  environment:
    Variables:
      key1: "value1"
      key2: "value2"
  tags:
    project: "test"
