apiVersion: aws.boundless.software/v1alpha1
kind: Iam
metadata:
  name: example-iam
spec:
  provider:
    region: us-east-1
  role:
    name: example-role
    policy:
      name: example-policy
      Statement:
        - Action:
            - iam:GetAccountPasswordPolicy
            - iam:ListVirtualMFADevices
          Effect: Allow
          Resource:
            - "*"
    policyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
    trustPolicy:
      Statement:
        - Action:
            - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: "s3.amazonaws.com"
  # user:
  #   name: example-user
  #   policy:
  #     name: example-policy
  #     Statement:
  #       - Action:
  #           - events:*
  #         Effect: Allow
  #         Resource:
  #           - "*"
  #   policyArns:
  #     - arn:aws:iam::aws:policy/AdministratorAccess
  # oidcProvider:
  #   url: https://oidc.eks.us-east-1.amazonaws.com/id/<oidc-provider-id>
  #   clientIdList:
  #     - "sts.amazonaws.com"
  #   thumbprintList:
  #     - <thumbprint>
  # policy:
  #   name: example-policy
  #   Statement:
  #     - Action:
  #         - s3:*
  #       Effect: Allow
  #       Resource: "*"
  # userGroup:
  #   name: example-group
  #   users:
  #     - example-user
  #   policyArns:
  #     # - arn:aws:iam::aws:policy/AdministratorAccess
  #     - arn:aws:iam::aws:policy/AmazonGlacierReadOnlyAccess
  #   policy:
  #     name: example-policy
  #     Statement:
  #       - Action:
  #           - iam:GetAccountPasswordPolicy
  #           - iam:ListVirtualMFADevices
  #         Effect: Allow
  #         Resource:
  #           - "*"
