apiVersion: aws.boundless.software/v1alpha1
kind: Eks
metadata:
  name: example-eks
spec:
  provider:
    region: us-east-1
  cluster:
    endpoint:
      public: true
      private: true
    logTypes:
      - scheduler
    subnetIds:
      - <subnetid1>
      - <subnetid2>
      - <subnetid3>    
      - <subnetid4>
      - <subnetid5>
      - <subnetid6>
    version: "1.30"
    nodeGroups:
      critical:
        amiType: BOTTLEROCKET_x86_64
        capacityType: ON_DEMAND
        diskSize: 50
        instanceTypes:
          - c5.xlarge
        labels:
          nodegroup: critical
        taints:
          - effect: NO_SCHEDULE
            key: nodeType
            value: critical
        tags:
          karpenter.sh/discovery: workload
        scalingConfig:
          desiredSize: 1
          maxSize: 2
          minSize: 1
        subnets:
          - <subnetid1>
          - <subnetid2>
          - <subnetid3>
        version: "1.30"

